apiVersion: v1
kind: Service
metadata:
  namespace: flink
  name: flink-taskmanager
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9249"
spec:
  type: ClusterIP
  ports:
  - name: prom
    port: 9249
  selector:
    app: flink
    component: taskmanager