apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flink-taskmanager
  namespace: flink
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flink-taskmanager
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50